apiVersion: druid.gardener.cloud/v1alpha1
kind: EtcdOperatorTask
metadata:
  name: on-demand-snapshot-task
  namespace: default
spec:
  type: OnDemandSnapshot
  etcdRef:
    name: etcd-test
    namespace: default
  config: 
    onDemandSnapshotConfig:
      snapshotType: full
      timeoutSeconds: 60
    testConfig:
      test: false
  ttlSecondsAfterFinished: 20 