// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	versioned "github.com/gardener/etcd-druid/client/clientset/versioned"
	internalinterfaces "github.com/gardener/etcd-druid/client/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/gardener/etcd-druid/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdOperatorTaskInformer provides access to a shared informer and lister for
// EtcdOperatorTasks.
type EtcdOperatorTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.EtcdOperatorTaskLister
}

type etcdOperatorTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEtcdOperatorTaskInformer constructs a new informer for EtcdOperatorTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEtcdOperatorTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEtcdOperatorTaskInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEtcdOperatorTaskInformer constructs a new informer for EtcdOperatorTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEtcdOperatorTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DruidV1alpha1().EtcdOperatorTasks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DruidV1alpha1().EtcdOperatorTasks(namespace).Watch(context.TODO(), options)
			},
		},
		&apicorev1alpha1.EtcdOperatorTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *etcdOperatorTaskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEtcdOperatorTaskInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *etcdOperatorTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1alpha1.EtcdOperatorTask{}, f.defaultInformer)
}

func (f *etcdOperatorTaskInformer) Lister() corev1alpha1.EtcdOperatorTaskLister {
	return corev1alpha1.NewEtcdOperatorTaskLister(f.Informer().GetIndexer())
}
