// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	versioned "github.com/gardener/etcd-druid/client/clientset/versioned"
	internalinterfaces "github.com/gardener/etcd-druid/client/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/gardener/etcd-druid/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdMemberInformer provides access to a shared informer and lister for
// EtcdMembers.
type EtcdMemberInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.EtcdMemberLister
}

type etcdMemberInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEtcdMemberInformer constructs a new informer for EtcdMember type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEtcdMemberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEtcdMemberInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEtcdMemberInformer constructs a new informer for EtcdMember type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEtcdMemberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DruidV1alpha1().EtcdMembers(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DruidV1alpha1().EtcdMembers(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DruidV1alpha1().EtcdMembers(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DruidV1alpha1().EtcdMembers(namespace).Watch(ctx, options)
			},
		},
		&apicorev1alpha1.EtcdMember{},
		resyncPeriod,
		indexers,
	)
}

func (f *etcdMemberInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEtcdMemberInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *etcdMemberInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1alpha1.EtcdMember{}, f.defaultInformer)
}

func (f *etcdMemberInformer) Lister() corev1alpha1.EtcdMemberLister {
	return corev1alpha1.NewEtcdMemberLister(f.Informer().GetIndexer())
}
