// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/etcd-druid/internal/task (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -package task -destination=mocks.go github.com/gardener/etcd-druid/internal/task Handler
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"

	task "github.com/gardener/etcd-druid/internal/task"
	logr "github.com/go-logr/logr"
	gomock "go.uber.org/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Admit mocks base method.
func (m *MockHandler) Admit(ctx context.Context) *task.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Admit", ctx)
	ret0, _ := ret[0].(*task.Result)
	return ret0
}

// Admit indicates an expected call of Admit.
func (mr *MockHandlerMockRecorder) Admit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Admit", reflect.TypeOf((*MockHandler)(nil).Admit), ctx)
}

// Cleanup mocks base method.
func (m *MockHandler) Cleanup(ctx context.Context) *task.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(*task.Result)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockHandlerMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockHandler)(nil).Cleanup), ctx)
}

// EtcdReference mocks base method.
func (m *MockHandler) EtcdReference() types.NamespacedName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EtcdReference")
	ret0, _ := ret[0].(types.NamespacedName)
	return ret0
}

// EtcdReference indicates an expected call of EtcdReference.
func (mr *MockHandlerMockRecorder) EtcdReference() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EtcdReference", reflect.TypeOf((*MockHandler)(nil).EtcdReference))
}

// Logger mocks base method.
func (m *MockHandler) Logger() logr.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(logr.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockHandlerMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockHandler)(nil).Logger))
}

// Name mocks base method.
func (m *MockHandler) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHandlerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHandler)(nil).Name))
}

// Run mocks base method.
func (m *MockHandler) Run(ctx context.Context) *task.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(*task.Result)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockHandlerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockHandler)(nil).Run), ctx)
}
