apiVersion: druid.gardener.cloud/v1alpha1
kind: EtcdOpsTask
metadata:
  name: on-demand-snapshot-task-2
  namespace: default
spec:
  etcdRef:
    name: etcd-test
    namespace: default
  config:
    onDemandSnapshotConfig:
      type: full #values: full, delta
      timeoutSeconds: 60
      isFinal: false
    
  ttlSecondsAfterFinished: 60
