// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdOperatorTaskLister helps list EtcdOperatorTasks.
// All objects returned here must be treated as read-only.
type EtcdOperatorTaskLister interface {
	// List lists all EtcdOperatorTasks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdOperatorTask, err error)
	// EtcdOperatorTasks returns an object that can list and get EtcdOperatorTasks.
	EtcdOperatorTasks(namespace string) EtcdOperatorTaskNamespaceLister
	EtcdOperatorTaskListerExpansion
}

// etcdOperatorTaskLister implements the EtcdOperatorTaskLister interface.
type etcdOperatorTaskLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdOperatorTask]
}

// NewEtcdOperatorTaskLister returns a new EtcdOperatorTaskLister.
func NewEtcdOperatorTaskLister(indexer cache.Indexer) EtcdOperatorTaskLister {
	return &etcdOperatorTaskLister{listers.New[*corev1alpha1.EtcdOperatorTask](indexer, corev1alpha1.Resource("etcdoperatortask"))}
}

// EtcdOperatorTasks returns an object that can list and get EtcdOperatorTasks.
func (s *etcdOperatorTaskLister) EtcdOperatorTasks(namespace string) EtcdOperatorTaskNamespaceLister {
	return etcdOperatorTaskNamespaceLister{listers.NewNamespaced[*corev1alpha1.EtcdOperatorTask](s.ResourceIndexer, namespace)}
}

// EtcdOperatorTaskNamespaceLister helps list and get EtcdOperatorTasks.
// All objects returned here must be treated as read-only.
type EtcdOperatorTaskNamespaceLister interface {
	// List lists all EtcdOperatorTasks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdOperatorTask, err error)
	// Get retrieves the EtcdOperatorTask from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.EtcdOperatorTask, error)
	EtcdOperatorTaskNamespaceListerExpansion
}

// etcdOperatorTaskNamespaceLister implements the EtcdOperatorTaskNamespaceLister
// interface.
type etcdOperatorTaskNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdOperatorTask]
}
