// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdMemberLister helps list EtcdMembers.
// All objects returned here must be treated as read-only.
type EtcdMemberLister interface {
	// List lists all EtcdMembers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdMember, err error)
	// EtcdMembers returns an object that can list and get EtcdMembers.
	EtcdMembers(namespace string) EtcdMemberNamespaceLister
	EtcdMemberListerExpansion
}

// etcdMemberLister implements the EtcdMemberLister interface.
type etcdMemberLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdMember]
}

// NewEtcdMemberLister returns a new EtcdMemberLister.
func NewEtcdMemberLister(indexer cache.Indexer) EtcdMemberLister {
	return &etcdMemberLister{listers.New[*corev1alpha1.EtcdMember](indexer, corev1alpha1.Resource("etcdmember"))}
}

// EtcdMembers returns an object that can list and get EtcdMembers.
func (s *etcdMemberLister) EtcdMembers(namespace string) EtcdMemberNamespaceLister {
	return etcdMemberNamespaceLister{listers.NewNamespaced[*corev1alpha1.EtcdMember](s.ResourceIndexer, namespace)}
}

// EtcdMemberNamespaceLister helps list and get EtcdMembers.
// All objects returned here must be treated as read-only.
type EtcdMemberNamespaceLister interface {
	// List lists all EtcdMembers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdMember, err error)
	// Get retrieves the EtcdMember from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.EtcdMember, error)
	EtcdMemberNamespaceListerExpansion
}

// etcdMemberNamespaceLister implements the EtcdMemberNamespaceLister
// interface.
type etcdMemberNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdMember]
}
