// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file contains hand-written DeepCopy methods for the EtcdMember types.
// These MUST be regenerated by running `cd api && make generate` before merging.
// The generated code in zz_generated.deepcopy.go will supersede these methods.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *EtcdMember) DeepCopyInto(out *EtcdMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new EtcdMember.
func (in *EtcdMember) DeepCopy() *EtcdMember {
	if in == nil {
		return nil
	}
	out := new(EtcdMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a hand-written deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *EtcdMemberList) DeepCopyInto(out *EtcdMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EtcdMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new EtcdMemberList.
func (in *EtcdMemberList) DeepCopy() *EtcdMemberList {
	if in == nil {
		return nil
	}
	out := new(EtcdMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a hand-written deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EtcdMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *EtcdMemberResourceStatus) DeepCopyInto(out *EtcdMemberResourceStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(MemberState)
		**out = **in
	}
	if in.SubState != nil {
		in, out := &in.SubState, &out.SubState
		*out = new(MemberSubState)
		**out = **in
	}
	if in.PeerTLSEnabled != nil {
		in, out := &in.PeerTLSEnabled, &out.PeerTLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DBSize != nil {
		in, out := &in.DBSize, &out.DBSize
		*out = new(int64)
		**out = **in
	}
	if in.DBSizeInUse != nil {
		in, out := &in.DBSizeInUse, &out.DBSizeInUse
		*out = new(int64)
		**out = **in
	}
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(MemberSnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastRestoration != nil {
		in, out := &in.LastRestoration, &out.LastRestoration
		*out = new(MemberRestorationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastDefragmentation != nil {
		in, out := &in.LastDefragmentation, &out.LastDefragmentation
		*out = new(MemberDefragmentationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Transitions != nil {
		in, out := &in.Transitions, &out.Transitions
		*out = make([]MemberTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new EtcdMemberResourceStatus.
func (in *EtcdMemberResourceStatus) DeepCopy() *EtcdMemberResourceStatus {
	if in == nil {
		return nil
	}
	out := new(EtcdMemberResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *MemberSnapshotStatus) DeepCopyInto(out *MemberSnapshotStatus) {
	*out = *in
	if in.LastFull != nil {
		in, out := &in.LastFull, &out.LastFull
		*out = new(SnapshotInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.LastDelta != nil {
		in, out := &in.LastDelta, &out.LastDelta
		*out = new(SnapshotInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.AccumulatedDeltaSize != nil {
		in, out := &in.AccumulatedDeltaSize, &out.AccumulatedDeltaSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new MemberSnapshotStatus.
func (in *MemberSnapshotStatus) DeepCopy() *MemberSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(MemberSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *SnapshotInfo) DeepCopyInto(out *SnapshotInfo) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
	if in.StartRevision != nil {
		in, out := &in.StartRevision, &out.StartRevision
		*out = new(int64)
		**out = **in
	}
	if in.EndRevision != nil {
		in, out := &in.EndRevision, &out.EndRevision
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new SnapshotInfo.
func (in *SnapshotInfo) DeepCopy() *SnapshotInfo {
	if in == nil {
		return nil
	}
	out := new(SnapshotInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *MemberRestorationStatus) DeepCopyInto(out *MemberRestorationStatus) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(RestorationType)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(OperationStatus)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new MemberRestorationStatus.
func (in *MemberRestorationStatus) DeepCopy() *MemberRestorationStatus {
	if in == nil {
		return nil
	}
	out := new(MemberRestorationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *MemberDefragmentationStatus) DeepCopyInto(out *MemberDefragmentationStatus) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(OperationStatus)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialDBSize != nil {
		in, out := &in.InitialDBSize, &out.InitialDBSize
		*out = new(int64)
		**out = **in
	}
	if in.FinalDBSize != nil {
		in, out := &in.FinalDBSize, &out.FinalDBSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new MemberDefragmentationStatus.
func (in *MemberDefragmentationStatus) DeepCopy() *MemberDefragmentationStatus {
	if in == nil {
		return nil
	}
	out := new(MemberDefragmentationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a hand-written deepcopy function, copying the receiver, writing into out.
func (in *MemberTransition) DeepCopyInto(out *MemberTransition) {
	*out = *in
	if in.SubState != nil {
		in, out := &in.SubState, &out.SubState
		*out = new(MemberSubState)
		**out = **in
	}
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is a hand-written deepcopy function, copying the receiver, creating a new MemberTransition.
func (in *MemberTransition) DeepCopy() *MemberTransition {
	if in == nil {
		return nil
	}
	out := new(MemberTransition)
	in.DeepCopyInto(out)
	return out
}
