// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	corev1alpha1 "github.com/gardener/etcd-druid/client/clientset/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEtcdMembers implements EtcdMemberInterface
type fakeEtcdMembers struct {
	*gentype.FakeClientWithList[*v1alpha1.EtcdMember, *v1alpha1.EtcdMemberList]
	Fake *FakeDruidV1alpha1
}

func newFakeEtcdMembers(fake *FakeDruidV1alpha1, namespace string) corev1alpha1.EtcdMemberInterface {
	return &fakeEtcdMembers{
		gentype.NewFakeClientWithList[*v1alpha1.EtcdMember, *v1alpha1.EtcdMemberList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("etcdmembers"),
			v1alpha1.SchemeGroupVersion.WithKind("EtcdMember"),
			func() *v1alpha1.EtcdMember { return &v1alpha1.EtcdMember{} },
			func() *v1alpha1.EtcdMemberList { return &v1alpha1.EtcdMemberList{} },
			func(dst, src *v1alpha1.EtcdMemberList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EtcdMemberList) []*v1alpha1.EtcdMember { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.EtcdMemberList, items []*v1alpha1.EtcdMember) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
