// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	corev1alpha1 "github.com/gardener/etcd-druid/client/clientset/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEtcdOperatorTasks implements EtcdOperatorTaskInterface
type fakeEtcdOperatorTasks struct {
	*gentype.FakeClientWithList[*v1alpha1.EtcdOperatorTask, *v1alpha1.EtcdOperatorTaskList]
	Fake *FakeDruidV1alpha1
}

func newFakeEtcdOperatorTasks(fake *FakeDruidV1alpha1, namespace string) corev1alpha1.EtcdOperatorTaskInterface {
	return &fakeEtcdOperatorTasks{
		gentype.NewFakeClientWithList[*v1alpha1.EtcdOperatorTask, *v1alpha1.EtcdOperatorTaskList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("etcdoperatortasks"),
			v1alpha1.SchemeGroupVersion.WithKind("EtcdOperatorTask"),
			func() *v1alpha1.EtcdOperatorTask { return &v1alpha1.EtcdOperatorTask{} },
			func() *v1alpha1.EtcdOperatorTaskList { return &v1alpha1.EtcdOperatorTaskList{} },
			func(dst, src *v1alpha1.EtcdOperatorTaskList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EtcdOperatorTaskList) []*v1alpha1.EtcdOperatorTask {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.EtcdOperatorTaskList, items []*v1alpha1.EtcdOperatorTask) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
