// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	scheme "github.com/gardener/etcd-druid/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdMembersGetter has a method to return a EtcdMemberInterface.
// A group's client should implement this interface.
type EtcdMembersGetter interface {
	EtcdMembers(namespace string) EtcdMemberInterface
}

// EtcdMemberInterface has methods to work with EtcdMember resources.
type EtcdMemberInterface interface {
	Create(ctx context.Context, etcdMember *corev1alpha1.EtcdMember, opts v1.CreateOptions) (*corev1alpha1.EtcdMember, error)
	Update(ctx context.Context, etcdMember *corev1alpha1.EtcdMember, opts v1.UpdateOptions) (*corev1alpha1.EtcdMember, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcdMember *corev1alpha1.EtcdMember, opts v1.UpdateOptions) (*corev1alpha1.EtcdMember, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.EtcdMember, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.EtcdMemberList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.EtcdMember, err error)
	EtcdMemberExpansion
}

// etcdMembers implements EtcdMemberInterface
type etcdMembers struct {
	*gentype.ClientWithList[*corev1alpha1.EtcdMember, *corev1alpha1.EtcdMemberList]
}

// newEtcdMembers returns a EtcdMembers
func newEtcdMembers(c *DruidV1alpha1Client, namespace string) *etcdMembers {
	return &etcdMembers{
		gentype.NewClientWithList[*corev1alpha1.EtcdMember, *corev1alpha1.EtcdMemberList](
			"etcdmembers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.EtcdMember { return &corev1alpha1.EtcdMember{} },
			func() *corev1alpha1.EtcdMemberList { return &corev1alpha1.EtcdMemberList{} },
		),
	}
}
