// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	scheme "github.com/gardener/etcd-druid/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdOperatorTasksGetter has a method to return a EtcdOperatorTaskInterface.
// A group's client should implement this interface.
type EtcdOperatorTasksGetter interface {
	EtcdOperatorTasks(namespace string) EtcdOperatorTaskInterface
}

// EtcdOperatorTaskInterface has methods to work with EtcdOperatorTask resources.
type EtcdOperatorTaskInterface interface {
	Create(ctx context.Context, etcdOperatorTask *corev1alpha1.EtcdOperatorTask, opts v1.CreateOptions) (*corev1alpha1.EtcdOperatorTask, error)
	Update(ctx context.Context, etcdOperatorTask *corev1alpha1.EtcdOperatorTask, opts v1.UpdateOptions) (*corev1alpha1.EtcdOperatorTask, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcdOperatorTask *corev1alpha1.EtcdOperatorTask, opts v1.UpdateOptions) (*corev1alpha1.EtcdOperatorTask, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.EtcdOperatorTask, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.EtcdOperatorTaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.EtcdOperatorTask, err error)
	EtcdOperatorTaskExpansion
}

// etcdOperatorTasks implements EtcdOperatorTaskInterface
type etcdOperatorTasks struct {
	*gentype.ClientWithList[*corev1alpha1.EtcdOperatorTask, *corev1alpha1.EtcdOperatorTaskList]
}

// newEtcdOperatorTasks returns a EtcdOperatorTasks
func newEtcdOperatorTasks(c *DruidV1alpha1Client, namespace string) *etcdOperatorTasks {
	return &etcdOperatorTasks{
		gentype.NewClientWithList[*corev1alpha1.EtcdOperatorTask, *corev1alpha1.EtcdOperatorTaskList](
			"etcdoperatortasks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.EtcdOperatorTask { return &corev1alpha1.EtcdOperatorTask{} },
			func() *corev1alpha1.EtcdOperatorTaskList { return &corev1alpha1.EtcdOperatorTaskList{} },
		),
	}
}
